In [39]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
#sns.set()

#Apply a fix to the statsmodels library
from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq, df)

In [41]:
data=pd.read_csv('Social_Network_Ads.csv')

In [43]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [45]:
x=data['EstimatedSalary']
y=data['Purchased']
x

0      19000
1      20000
2      43000
3      57000
4      76000
       ...  
395    41000
396    23000
397    20000
398    33000
399    36000
Name: EstimatedSalary, Length: 400, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split

In [49]:
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.25, random_state=0)

In [51]:
len(x_train)

300

In [53]:
len(x_test)

100

In [57]:
#data could be scaled but it's not necessary
from sklearn.preprocessing import StandardScaler

In [61]:
x_train = x_train.values.reshape(-1, 1) if isinstance(x_train, pd.Series) else x_train
x_test = x_test.values.reshape(-1, 1) if isinstance(x_test, pd.Series) else x_test

sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [63]:
x_train

array([[-0.88670699],
       [ 1.46173768],
       [-0.5677824 ],
       [ 1.89663484],
       [-1.40858358],
       [ 0.99784738],
       [-0.79972756],
       [-0.24885782],
       [-0.5677824 ],
       [-0.19087153],
       [-1.29261101],
       [-0.5677824 ],
       [ 0.09905991],
       [-0.59677555],
       [-1.17663843],
       [-0.13288524],
       [ 1.78066227],
       [ 0.56295021],
       [ 0.35999821],
       [-0.53878926],
       [-1.58254245],
       [ 0.93986109],
       [ 1.22979253],
       [ 1.08482681],
       [-0.48080297],
       [-0.30684411],
       [-0.8287207 ],
       [ 1.8676417 ],
       [ 1.25878567],
       [ 2.27354572],
       [-1.58254245],
       [-0.79972756],
       [-1.46656987],
       [ 2.30253886],
       [ 0.76590222],
       [-0.30684411],
       [ 0.76590222],
       [ 0.56295021],
       [ 0.07006676],
       [-1.26361786],
       [-0.01691267],
       [ 0.35999821],
       [ 0.12805305],
       [ 0.30201192],
       [ 0.07006676],
       [ 2

In [65]:
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=0) 

In [67]:
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [71]:
#scale values back to original form
y_pred=classifier.predict(x_test)

In [73]:
y_pred = y_pred.to_numpy().reshape(len(y_pred), 1) if isinstance(y_pred, pd.Series) else y_pred.reshape(len(y_pred), 1)
y_test = y_test.to_numpy().reshape(len(y_test), 1) if isinstance(y_test, pd.Series) else y_test.reshape(len(y_test), 1)

# Concatenate the reshaped arrays
result = np.concatenate((y_pred, y_test), axis=1)
print(result)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]]


In [75]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [79]:
cm=confusion_matrix(y_test, y_pred)

In [81]:
cm

array([[66,  2],
       [18, 14]], dtype=int64)

In [85]:
accuracy_score(y_test, y_pred)

0.8