In [3]:
#The simplest,, most flexible way to work with scalers, vectors, matrices is by using arrays
#numpy is optimized for such operations
import numpy as np

In [92]:
#Scalers
s=5

In [93]:
s

5

In [94]:
#Vectors
#By default, v is a row vector
v=np.array([5,-2,4])
v

array([ 5, -2,  4])

In [13]:
#Matrix. This matrix can be seen as containing 2 vectors
m=np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [96]:
#type(x) returns data type of x var
type(s)

int

In [97]:
type(v)

numpy.ndarray

In [98]:
type(m)

numpy.ndarray

In [99]:
#ndarray stands for n dimentional array
#v is a 1D array, m is a 2D array

In [100]:
#to convert integer into a array
s_array=np.array(5)
s_array

array(5)

In [101]:
type(s_array)

numpy.ndarray

In [102]:
#shape returns shape (dimensions) of a var
m.shape

(2, 3)

In [103]:
v.shape

(3,)

In [104]:
#reshape gives an array a new shape w/o changing its data. It can be used to create a row or a column vector
#x.reshape(desired form). There are 2 possibilities-(a) 1,3- gives row vector (2) 3, 1- gives column vector
v.reshape(1,3)

array([[ 5, -2,  4]])

In [105]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [106]:
#int objects don't have shape
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [108]:
#it's empty as a scaler is a zero D object
s_array.shape

()

In [19]:
# adding and substracting matrices
m2=np.array([[3,6,2],[52,6,2]])
m2

array([[ 3,  6,  2],
       [52,  6,  2]])

In [112]:
m+m2

array([[ 8, 18,  8],
       [49,  6, 16]])

In [114]:
m-m2

array([[  2,   6,   4],
       [-55,  -6,  12]])

In [116]:
# adding and substracting vectors
v1=np.array([7,9,1])

In [118]:
v+v1

array([12,  7,  5])

In [120]:
v-v1

array([ -2, -11,   3])

In [122]:
#adding and substracting scalers
5+5, 5-1

(10, 4)

In [124]:
#exceptions (addition with scaler) can work in python
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [126]:
m+1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [128]:
v+1

array([ 6, -1,  5])

In [130]:
m+np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [132]:
v+np.array([1])

array([ 6, -1,  5])

In [134]:
#Transposing matrices
A=np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [136]:
#array.T returns transpose of an array
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [138]:
B=np.array([[5,3],[-2,1]])
B

array([[ 5,  3],
       [-2,  1]])

In [140]:
B.T

array([[ 5, -2],
       [ 3,  1]])

In [7]:
C=np.array([[5,12],[7,6],[-3,0],[23,14]])
C

array([[ 5, 12],
       [ 7,  6],
       [-3,  0],
       [23, 14]])

In [9]:
C.T

array([[ 5,  7, -3, 23],
       [12,  6,  0, 14]])

In [148]:
#Any scaler transposed = itself
s=np.array([5])
s

array([5])

In [150]:
s.T

array([5])

In [156]:
#transposing vector=vector because in python 1D arrays don't get transposed
v.T

array([ 5, -2,  4])

In [158]:
#to transpose a vector, reshape it into a 3 by 1 or a 2D array
v_reshaped=v.reshape(1,3)
v_reshaped

array([[ 5, -2,  4]])

In [160]:
v_reshaped.T

array([[ 5],
       [-2],
       [ 4]])

In [9]:
#np.dot() returns 2 objects' dot product
x=np.array([2,8,-4])
y=np.array([1,-7,3])
np.dot(x,y)

-66

In [11]:
# scalar * scalar
np.dot(5,6)

30

In [13]:
#scalar * vector
5*x

array([ 10,  40, -20])

In [11]:
#scalar * matrix
5*C

array([[ 25,  60],
       [ 35,  30],
       [-15,   0],
       [115,  70]])

In [33]:
#matrix * matrix requires np.dot(x,y) method
m3=np.array([[3,5,8,4],[11,9,6,10],[12,13,2,7]])
m3

array([[ 3,  5,  8,  4],
       [11,  9,  6, 10],
       [12, 13,  2,  7]])

In [39]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [41]:
np.dot(m,m3)

array([[219, 211, 124, 182],
       [159, 167,   4,  86]])

In [52]:
m4=np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
m4

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [54]:
m5=np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])
m5

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [56]:
np.dot(m4,m5)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])