In [1]:
import numpy as np

In [5]:
m1=np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [7]:
#tensors can be stored in ndarrays
m2=np.array([[99,24,6],[-2,64,1]])
m2

array([[99, 24,  6],
       [-2, 64,  1]])

In [9]:
#to create a tensor
t=np.array([m1,m1])

In [11]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 5, 12,  6],
        [-3,  0, 14]]])

In [13]:
#t contains 2 matrices, 2 X 3 each
t.shape

(2, 2, 3)

In [17]:
#to manually create a tensor
t_manual=np.array([[[3,6,7],[11,66,24]],[[55,63,67],[4,1,5]]])
t_manual

array([[[ 3,  6,  7],
        [11, 66, 24]],

       [[55, 63, 67],
        [ 4,  1,  5]]])